import = [
    #"~/.config/alacritty/catppuccin-mocha.toml"
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "CaskaydiaMono NFM"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono NFM"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaMono NFM"
style = "Regular"

[window]
opacity = 0.9
dynamic_title = true

[window.padding]
x = 5
y = 5

[window.class]
instance = "alacritty"
general = "alacritty"
