import = [
    #"~/.config/alacritty/catppuccin-mocha.toml"
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[window]
opacity = 0.9
dynamic_title = true

[window.padding]
x = 5
y = 5

[window.class]
instance = "alacritty"
general = "alacritty"
