import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "CaskaydiaMono NFM"
style = "Bold"

[font.italic]
family = "CaskaydiaMono NFM"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaMono NFM"
style = "Bold Italic"

[font.normal]
family = "CaskaydiaMono NFM"
style = "Regular"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

