'$schema' = 'https://starship.rs/config-schema.json' # Editor completions

add_newline = true            # Add an empty line between prompts
scan_timeout = 10             # Only wait 10ms when checking files under CWD
command_timeout = 500         # Only wait 100ms when executing commands
palette = 'catppuccin_frappe'

format = '''
$os$directory$git_branch$git_status$c$lua$python$rust$time
$character
'''

[c]
detect_files = ['Makefile']
format = '[$symbol($name(-$version))  ]($style)'
style = 'bg:base fg:green bold'
symbol = 'C '

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[directory]
truncate_to_repo = false
truncation_symbol = '…/'
style = 'bg:base fg:sapphire bold'
format = '[$path]($style)[$read_only]($read_only_style)[  ]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'
style = 'bg:base fg:mauve bold'

[git_status]
format = '[\[$all_status$ahead_behind\]]($style)[  ](bg:base fg:mauve bold)'
style = 'bg:base fg:red bold'

[lua]
format = '[$symbol(${version} )  ]($style)'
style = 'bg:base fg:yellow bold'

[package]
disabled = true

[os]
disabled = false
format = '[$symbol]($style)[](bg:mantle fg:crust bold)[](bg:base fg:mantle bold)[ ](bg:base bold)'
style = 'bg:crust bold'

[os.symbols]
Arch = ' 🐧 '

[python]
format = '[${symbol}${pyenv_prefix}(${version})  ]($style)'
style = 'bg:base fg:yellow bold'

[rust]
format = '[$symbol($version)  ]($style)'
style = 'bg:base fg:yellow bold'

[time]
format = '[🕓️ ](bg:base bold)[$time ]($style)[](fg:base bold)'
style = 'bg:base fg:pink bold'
time_format = '%H:%M'
disabled = false

[palettes.catppuccin_frappe]
rosewater = '#f2d5cf'
flamingo = '#eebebe'
pink = '#f4b8e4'
mauve = '#ca9ee6'
red = '#e78284'
maroon = '#ea999c'
peach = '#ef9f76'
yellow = '#e5c890'
green = '#a6d189'
teal = '#81c8be'
sky = '#99d1db'
sapphire = '#85c1dc'
blue = '#8caaee'
lavender = '#babbf1'
text = '#c6d0f5'
subtext1 = '#b5bfe2'
subtext0 = '#a5adce'
overlay2 = '#949cbb'
overlay1 = '#838ba7'
overlay0 = '#737994'
surface2 = '#626880'
surface1 = '#51576d'
surface0 = '#414559'
base = '#303446'
mantle = '#292c3c'
crust = '#232634'
