#!/usr/bin/env bash

cp "$HOME/.bashrc" "$DOTFILES/bash/.bashrc"
cp "$HOME/.bash_profile" "$DOTFILES/bash/.bash_profile"
cp "$HOME/.gitconfig" "$DOTFILES/git/.gitconfig"
cp "$XDG_CONFIG_HOME/starship.toml" "$DOTFILES/starship/starship.toml"

cp -r "$HOME/themes" "$DOTFILES"

declare -a XDG_CONFIG_DIRS=("alacritty" "fontconfig" "hypr" "nvim" "rofi" "swaylock" "waybar" "wlogout")

for DIR in "${XDG_CONFIG_DIRS[@]}"; do
    cp -r "$XDG_CONFIG_HOME/$DIR" "$DOTFILES"
done
