#!/usr/bin/env bash

# ~ copy dotfiles into the repo for staging ~

cp "$HOME/.bashrc" "$DOTFILES/.bashrc"
cp "$HOME/.bash_profile" "$DOTFILES/.bash_profile"
cp "$XDG_CONFIG_HOME/alacritty/alacritty.toml" "$DOTFILES/alacritty.toml"
cp "$HOME/.tmux.conf" "$DOTFILES/.tmux.conf"

# copy nvim config, make sure to delete the lazy-lock.json
cp -r "$XDG_CONFIG_HOME/nvim" "$DOTFILES"

