#!/usr/bin/env bash

set -euo pipefail

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

function try_link {
	if [ -L "$XDG_CONFIG_HOME/$1" ]; then
		if [ -e "$XDG_CONFIG_HOME/$1" ]; then
			echo "Config link for $1 is good; skipping..."
			return 0
		else
			echo -n "Config link for $1 is broken; removing... "
			rm "$XDG_CONFIG_HOME/$1"
		fi
	fi

	ln -s "$HOME/dotfiles/$1" "$XDG_CONFIG_HOME/$1"
	echo "Linked config for $1"
}

try_link nvim
try_link fish
try_link kitty
try_link git
try_link fontconfig
try_link mise
try_link fastfetch

if [[ "$(uname -s)" =~ Linux ]]; then
    try_link niri
    try_link noctalia
    try_link systemd
fi
