#!/usr/bin/env bash

if [ -z ${DOTFILES+x} ]; then
    DOTFILES=$(pwd)
fi

if [ -z ${XDG_CONFIG_HOME+} ]; then
    XDG_CONFIG_HOME="$HOME"/.config
    mkdir -p $XDG_CONFIG_HOME
fi

cp "$DOTFILES/bash/.bashrc" "$HOME/.bashrc"
cp "$DOTFILES/bash/.bash_profile" "$HOME/.bash_profile"
cp "$DOTFILES/starship/starship.toml" "$XDG_CONFIG_HOME/starship.toml"

cp -r "$DOTFILES/themes" "$HOME"

declare -a XDG_CONFIG_DIRS=("alacritty" "fontconfig" "hypr" "nvim" "rofi" "swaylock" "waybar" "wlogout")

for DIR in "${XDG_CONFIG_DIRS[@]}"; do
    cp -r "$DOTFILES/$DIR" "$XDG_CONFIG_HOME"
done
