#!/usr/bin/bash

# params:
#   1. a regex search target
#   2. (optional) a file to localize the search to; if not given, the whole cwd-tree will be searched and modified
#
# dependencies:
#   1. ripgrep (rg)
#   2. sed
#   3. xargs

EXPR=$1
DOMAIN=${2:-.}

rg -l "$EXPR" "$DOMAIN" | xargs sed -i "/${EXPR}/d"

