#!/usr/bin/env bash

DONE_SUB="> :checkbox-checked:"
PROG_SUB="> :checkbox-deferred:"
WAIT_SUB="> :checkbox-unchecked:"
INFO_SUB="> :information_source:"

pushd $DEX > /dev/null
git pull

if [ $# -ne 1 ]; then
    file=$(find journal -name '*.md' | sort -r | fzf)
else
    file=$1
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
    TAIL=gtail
    HEAD=ghead
    SED=gsed
else
    TAIL=tail
    HEAD=head
    SED=sed
fi

markdown-extract "Summary" $file | $TAIL -n +3 | $HEAD -n -1 | $SED -e "s/✅/$DONE_SUB/g" | $SED -e "s/🚧/$PROG_SUB/g" | $SED -e "s/❌/$WAIT_SUB/g" | $SED -e "s/ℹ/$INFO_SUB/g" | $SED -e "s/^$/> /g"
popd > /dev/null
