#!/usr/bin/env fish

set --local year (date +%Y)
set --local cwd (pwd)

cd "$DEX/journal/$year"

set --local choice (find . -type f | sort -r | fzf)
sed -n "/### Summary/,\$p" <$choice \
    | tail -n +5 \
    | sed "s/➡️/-/g" \
    | sed "s/🎥/:zoom:/g" \
    | sed "s/⏳/:waiting:/g" \
    | sed "s/⌨️/:afk:/g" \
    | sed "s/🪾/:pr-open:/g" \
    | sed "s/🌳/:pr-merged:/g" \
    | sed "s/❗️/:github-issue:/g" \
    | sed "s/🚧/:workingonit:/g" \
    | sed "s/\[\[/[​[/g" \
    | kcopy

cd $cwd
